from pathlib import Path
import json,datetime
from decimal import Decimal
r=Path(__file__).resolve().parents[1];o=r/'outputs';seal=json.loads((r/'blind/SCORE_SEAL.json').read_text());reveal=json.loads((o/'UNBLINDING.json').read_text());assert seal['time']<reveal['time']
rows=[]
for name in ['E1b','ADK_plain','E2','E3','E4']:
 e=r/name;f=json.loads((e/'FREEZE.json').read_text());runs=json.loads((e/'outputs/private_run_manifest.json').read_text());usage=[json.loads(x)for x in(e/'outputs/paid_usage.jsonl').read_text().splitlines()]
 starts=[x['receipt']['started_at_utc']for x in runs];assert all(f['time']<t for t in starts),(name,f['time'],min(starts))
 rows.append({'experiment':name,'freeze':f'{name}/FREEZE.json','freeze_time':f['time'],'first_start':min(starts),'freeze_before_first_start':True,'planned':len(f['run_order']),'completed_attempts':len(runs),'original_answers':[{'run':x['run'],'sha256':x['receipt'].get('answer_sha256'),'status':x['receipt']['status']}for x in runs],'usage_file':f'{name}/outputs/paid_usage.jsonl','requests':len(usage),'cost_usd':str(sum(Decimal(str(x['cost']))for x in usage)),'archive':f'archives/{name}_frozen_evidence.tar.gz','score_seal':'blind/SCORE_SEAL.json','unblind':'outputs/UNBLINDING.json'})
record={'created':datetime.datetime.now(datetime.timezone.utc).isoformat(),'experiments':rows,'score_seal':seal,'unblinding_time':reveal['time'],'score_sealed_before_reveal':True,'physical_admission':{'status':'PASS','time':'2026-09-10T11:34:26.893877+00:00','path':'adk_physical/FOUR_STANDARD_PHYSICAL_ADMISSION.json','scope':'ADK complete-molecule intramolecular distances; six predeclared pairs all frames plus specified extrema; GROMACS and local <=0.01A'},'independent_recompute':['outputs/ADK_INDEPENDENT_RECOMPUTE.json','outputs/E0_N18_ORIGINAL_MEAN_CHECK.json'],'historical_reconciliation':'outputs/COST_RECONCILIATION.json','source_relations':'outputs/ADK_PAPER_RELATIONSHIPS.md','checker_scope':'outputs/E1A_CHECK_COVERAGE_AUDIT.json','check_results':'outputs/FINAL_VALIDATION.json','deviations':'outputs/DEVIATIONS.md','human_interventions':'No in-run scientific prompts; no paid reruns for quality. Developer prepares inputs and scores outputs, disclosed. User-forwarded review received after E2 and after E3 started; freezes unchanged.','publication':'Commit and remote readback recorded in delivery receipt outside the self-referential commit payload','new_total_usd':str(sum(Decimal(x['cost_usd'])for x in rows))}
(o/'WORK_EVIDENCE_LEDGER.json').write_text(json.dumps(record,ensure_ascii=False,indent=2));print('Ledger written with',len(rows),'experiments; freeze<first call and seal<reveal verified')
