from pathlib import Path
import csv,json,datetime
w=Path.cwd();r=Path(__file__).resolve().parents[1];h=w/'autoresearch/tasks/dynamics_atlas_hsp90_first_round_v3_20260910';d=w/'autoresearch/tasks/dynamics_atlas_adk_plain_agent_v1_20260910';t=w/'autoresearch/tasks/dynamics_atlas_rules_incremental_value_protocol_20260909'
h2=h/'runs/HSP90_Q01_A_9ff587f6/answer.md';b1=h/'runs/HSP90_Q01_B_b909c96b/answer.md';b2=h/'runs/HSP90_Q01_B_8813dc0f/answer.md';d1=d/'runs/DHFR_Q01_A_07534f46/answer.md';d2=d/'runs/DHFR_Q01_A_ef5da470/answer.md'
items=[('HSP90','wrong threshold-specific initial direction counts',h2,'11/20','D','feedback','NOT_RUN','number presence alone cannot detect wrong threshold linkage'),('HSP90','4/20 vs5/20 internal inconsistency',h2,'有 4/20','D','feedback','NOT_RUN','requires linking same metric and threshold'),('HSP90','50point opposite candidate falsely zero',h2,'50 点时无 opposite','D','feedback','NOT_RUN','source50point count1 not0'),('HSP90','RMP special-method prerequisite transferred',b1,'RMP restraint','C','card','NOT_RUN','method-family scoping candidate'),('HSP90','RMP prerequisite transferred in another output',b2,'RMP restraint','C','card','NOT_RUN','same failure class, distinct output; not independent source'),('HSP90','endpoint bins called regular',b1,'420个常规箱','D','template','NOT_RUN','minor wording only; no core scientific count error'),('DHFR','A1 analyzes physically mismatched wrapped distances',d1,'18.14→12.16','B','code','YES','E1a defect1 source comparison; Agent missed input defect'),('DHFR','A1 N18 near-distance percentage mistranscription',d1,'9.2→15.7','D','feedback','NOT_RUN','originaltable9.09→44.24%; separate from upstream physical defect'),('DHFR','A1 W22 near-distance percentage mistranscription',d1,'0.9→33.1','D','feedback','NOT_RUN','originaltable1.92→80.30%'),('DHFR','A2 interprets erroneous large-distance tail as switching',d2,'构象切换','B','code','YES','E1a detects underlying input mismatch; downstream interpretation prevention untested'),('DHFR','A1 L28R N18 mean mistranscription reverses original-table direction',d1,'19.10→19.69','D','feedback','NOT_RUN','independent E0_N18_ORIGINAL_MEAN_CHECK:19.64772281→18.50047205, n990; original defective table arithmetic only, not physical truth'),('Q05','constructed NOE bounds misaligned by atom pair',t/'runs/Q05_C_4a249b26/answer.md','4.35','D','feedback','NOT_RUN','independent audit maximum2.75049; cannot fix by number presence'),('T4L','acknowledgment overwrites scientific submitted answer',t/'runs/T4L_C_be4d6c40/answer.md','已提交','delivery','code','YES','prior offline replay in DEVELOPMENT_REPORT lines40,54; belongs delivery mechanism, not scientific ceiling evidence')]
rows=[]
for i,(round,error,path,needle,layer,form,replay,note)in enumerate(items,1):
 lines=path.read_text().splitlines();found=[(j+1,l)for j,l in enumerate(lines)if needle in l];assert found,(path,needle);ln,quote=found[0];rows.append({'id':i,'error':error,'round':round,'observed_in':str(path.relative_to(w)),'layer_that_would_catch':layer,'form':form,'evidence_path':str(path.relative_to(w))+':'+str(ln),'source_quote':quote,'detected_on_replay':replay,'replay_scope_and_limit':note})
with(r/'outputs/E0_RETROSPECTIVE_AUDIT.csv').open('w')as f:
 writer=csv.DictWriter(f,fieldnames=rows[0].keys());writer.writeheader();writer.writerows(rows)
counts={'rows':len(rows),'unique_original_answers':len({x['observed_in']for x in rows}),'candidate_code_rows':sum(x['form']=='code'for x in rows),'candidate_guidance_rows':sum(x['form']=='card'for x in rows),'candidate_framing_rows':0,'actual_replay_detected_rows':sum(x['detected_on_replay']=='YES'for x in rows),'not_causal_prevention_counts':True,'unit':'observations in exposed output artifacts; correlated errors, not independent science cases','framing_gap':'5/5/10 subdivision absent is not retroactively scored an error because original question did not require it','reviewed_answer_count':8,'time':datetime.datetime.now(datetime.timezone.utc).isoformat()};(r/'outputs/E0_COUNTS.json').write_text(json.dumps(counts,indent=2));print(counts)
