from pathlib import Path
import json,shutil,csv,sys,subprocess
w=Path.cwd();r=Path(__file__).resolve().parents[1];s=r.parent;t=w/'autoresearch/tasks/dynamics_atlas_rules_incremental_value_protocol_20260909';rt=w/'dynamics-atlas-harness-luna-runtime-v1/agent_experiments/luna_runtime_v1';sys.path.insert(0,str(rt));from render_active_rules import render
rows=list(csv.DictReader((w/'autoresearch/tasks/dynamics_atlas_literature_card_male_pilot_20260805/outputs/ruleset/v0_1/rule_registry.tsv').open()));reg={x['rule_id']:x for x in rows};families=json.loads((rt/'paper_method_family.json').read_text());classes={'forward_bridge','forward_implementation','inverse_model','reweighting','integration_operator','uncertainty_integration','uncertainty_decomposition','artifact_exclusion'};cards={}
for row in rows:
 if row['rule_class']not in classes:continue
 fam=families[row['paper_id']]['method_families'];text='\n'.join([f"方法卡 {row['rule_id']}",f"适用方法族：{', '.join(fam)}",f"要核对：{row['proposed_project_rule']}",f"方法/算子：{row['integration_operator']}",f"依据：{row['paper_finding']}",f"来源：{row['paper_title']}；{row['source_locator']}",f"迁移范围：{row['transfer_scope']}",'可质疑：本卡是项目归纳；只有具体方法与物理对象适用时才执行。'])+'\n';cards[row['rule_id']]={'families':fam,'text':text}
(r/'method_cards').mkdir(exist_ok=True)
for id,v in cards.items():(r/'method_cards'/f'{id}.md').write_text(v['text'])
e=r/'E3';counts={};methods={'Q-H2':['MD_TRAJECTORY','NMR'],'Q05':['MD_TRAJECTORY','NMR','SAXS'],'DHFR':['MD_TRAJECTORY'],'ADK':['MD_TRAJECTORY']}
for q in ['Q-H2','Q05']:
 c=e/'cases'/q;(c/'hidden').mkdir(parents=True,exist_ok=True)
 if q=='Q-H2':
  shutil.copytree(s/'round2_dpr/cases/Q-H2/common',c/'common',dirs_exist_ok=True);shutil.copytree(s/'round2_dpr/cases/Q-H2/hidden',c/'hidden',dirs_exist_ok=True)
 else:
  shutil.copytree(t/'cases/Q05',c/'common',dirs_exist_ok=True);(c/'common/CHECK_SCOPE.txt').unlink(missing_ok=True)
  (c/'common/FIELD_DEFINITIONS.md').write_text('本包复用9月9日已暴露的Q05作者资料。各数据列与单位以作者README/文件头为准；reference_only是作者结果，不是本次新计算。可以核对现有作者预测与实验，也可以选已有方法计算，不要求新优化。详见inputs_and_method README。未提供完整独立实验或未验证的补充材料；不补造。\n')
  m=json.loads((s/'round2_dpr/cases/Q-H2/hidden/metadata.json').read_text());m['case'].update(case_id='Q05',system_name='Bengtsen2020 nanodisc',scientific_claim=(c/'common/QUESTION.txt').read_text());m['case']['observability_target']={'event_signature':'SAXS NOE cross-observable consistency','target_time_scale':'deposited saved frames and experimental averages','target_spatial_scale':'nanodisc solution ensemble','source_locator':'QUESTION.txt;paper.txt'};base=m['evidence_items'][0];m['evidence_items']=[]
  for method,loc,quantity in [('MD_TRAJECTORY','molecular_dynamics_simulations/inputs_and_method/README.md','candidate conformations'),('SAXS','SAXS_and_SANS/README.md','scattering intensity versus q'),('NMR','BME_reweight/inputs_and_method/README.md','NOE averaged distance bounds')]:
   x=json.loads(json.dumps(base));x.update(source_id='q05_'+method,method_id=method,modality=method,source_locator=loc,construct_and_condition='Bengtsen2020 nanodisc per author method',native_observable=quantity,estimand='source-local cross-observable consistency',spatial_support='nanodisc',unit_or_aggregation='native units per author file');x['time_semantics'].update(source_support=loc,observation_window='as author deposited files; not independent frames');x['detection_boundary'].update(source_locator=loc,sampling_or_sensitivity_basis='author method and available forward predictions');m['evidence_items'].append(x)
  m['comparisons']=[];(c/'hidden/metadata.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));cmd=[sys.executable,str(w/'autoresearch/tasks/dynamics_atlas_metadata_selector_validation_20260813/scripts/select_review_obligations.py'),'--input',str(c/'hidden/metadata.json'),'--output',str(c/'hidden/obligations.json'),'--receipt',str(c/'hidden/selector_receipt.json'),'--run-id',q,'--method-scope',str(w/'autoresearch/tasks/dynamics_atlas_hsp90_first_round_v3_20260910/cases/HSP90_Q01/hidden/method_scope_dev_copy.json')];p=subprocess.run(cmd,capture_output=True,text=True);assert p.returncode==0,p.stdout+p.stderr
  rubric={'core_units':['at least one actual correctly calculated informative comparison using native experimental and predicted data; any established equivalent method accepted','source-local SAXS/NOE compatibility described separately without a universal all-observables success claim','fitted versus prediction evidence correctly separated, author weights or reference stats not claimed as own new optimization','proper native averaging/uncertainty interpretation for whichever comparison performed; e.g.NOEmethyl truepairbounds not fabricated array','finite candidate support, uncertainty/identifiability and concrete next discriminating analysis; no unique equilibrium/dynamics validation'],'reference_examples':{'SAXS_mean_standardized_residual_squared_author_joint':1.915230735,'HN_upper_violations':[47,292],'methyl_upper_violations':[8,40],'methyl_max_excess_A':2.75049},'tolerances':{'distance_A':.02,'chi_squared_mean':.02},'source':'SCIENCE_AUDIT_ZH.md plus independent source_check json; developer references not mounted','alternatives':'No requirement to choose reweighting or any expected operator; correct alternate useful calculation earns unit1'};(c/'hidden/rubric.json').write_text(json.dumps(rubric,ensure_ascii=False,indent=2))
 for arm in ['P','R_old','R_scoped']:(c/f'arm_{arm}').mkdir(exist_ok=True)
 shutil.copy2(t/'runtime/ACTIVE_RULES_ZH.md',c/'arm_P/GUIDANCE.md')
 if q=='Q-H2':shutil.copy2(s/'round2_dpr/cases/Q-H2/arm_R/GUIDANCE.md',c/'arm_R_old/GUIDANCE.md')
 else:
  ob=json.loads((c/'hidden/obligations.json').read_text());ob['method_families']=methods[q];text,unmapped,receipt=render(ob,reg);assert not unmapped;(c/'arm_R_old/GUIDANCE.md').write_text(text+'\n以上提醒可质疑。\n');(c/'hidden/render_receipt.json').write_text(json.dumps(receipt,indent=2))
 selected=[id for id,v in cards.items()if set(v['families'])&set(methods[q])];text='\n'.join(cards[id]['text']for id in selected);(c/'arm_R_scoped/GUIDANCE.md').write_text(text);counts[q]={'methods':methods[q],'selected':selected,'count':len(selected),'P_chars':(c/'arm_P/GUIDANCE.md').stat().st_size,'R_old_chars':(c/'arm_R_old/GUIDANCE.md').stat().st_size,'R_scoped_chars':len(text)}
for q in ['DHFR','ADK']:
 selected=[id for id,v in cards.items()if set(v['families'])&set(methods[q])];counts[q]={'methods':methods[q],'selected':selected,'count':len(selected),'scope':'MD analysis only; experimental paper context does not imply quantitative forward analysis'}
(r/'outputs/E3_CARD_RETRIEVAL.json').write_text(json.dumps(counts,ensure_ascii=False,indent=2));(e/'DESIGN.json').write_text(json.dumps({'cases':['Q-H2','Q05'],'arms':['P','R_old','R_scoped'],'replicates':4,'cap_usd':.55,'seed':2026091043,'exposure':'both exposed; no held-out claim','irrelevant_terms':'Count affirmative adoption of R0/dye/AV/RMP restraint as necessary here, not negations or faithful source descriptions','success':'R_scoped zero inapplicable-term adoption and corecorrect>=both P andR_old percase; report all other errors/cost'},indent=2))
e=r/'E4'
for q in ['HSP90_Q01','Q-A1']:
 c=e/'cases'/q;(c/'hidden').mkdir(parents=True,exist_ok=True)
 if q=='Q-A1':shutil.copytree(r/'ADK_plain/cases/Q-A1/common',c/'common',dirs_exist_ok=True)
 else:
  shutil.copytree(s/'round2_dpr/cases/Q-H2/common',c/'common',dirs_exist_ok=True);orig=w/'autoresearch/tasks/dynamics_atlas_hsp90_first_round_v3_20260910/cases/HSP90_Q01/common/QUESTION.txt';shutil.copy2(orig,c/'common/QUESTION.txt')
 split=('请分别回答：(1)几何/接触读数在两种起始轨迹里出现哪些方向变化？区分首次持续方向后变化与曾出现开放方向；(2)结合提供的两套原生NOE绝对违例，有哪些轨迹支持接近参照状态，哪些仍偏离两者？(3)现有资料对完整物理转变、比例或速率能支持到什么程度？写清读数、窗口、统计单位和剩余解释。分析方法由你选择。'if q=='HSP90_Q01'else'请分别回答：(1)开/闭起始轨迹的LID–CORE和NMP–CORE距离分布是否分离？(2)各条轨迹首末10%保存帧中两个结构域的距离变化幅度和方向是什么？(3)这些时间信息能否确定ATP响应的闭合顺序，哪些解释仍未排除？结合论文说明条件与测量差异，分析方法由你选择。')
 (c/'arm_SPLIT').mkdir(exist_ok=True);(c/'arm_SPLIT/QUESTION.txt').write_text(split);(c/'hidden/question_split.md').write_text('Original and split share identical data and scoring; split changes explicit requests. This estimates framing package including increased specificity, not semantic-equivalent paraphrase.\n'+split)
 units=(['5/4/1 opposite persistent runs and10everO at5pts, open0opposite; distinguish events','closed initial5open5lateropen10neveropen when computed; avoid requiredomission as factualerror','nativeNOE9relative1partial among10O, open18agreement at1A','direction vsabsolute reference vsphysicaltransition explicitly separated','finite source/threshold/window; no equilibrium or transitionrate upgrade']if q=='HSP90_Q01'else['LIDmedian33.568/30.638;NMP26.638/26.036, overlap documented','openNMP+.071LID+2.290;closedNMP+1.091LID+1.176 first/last10%','distances do not show a universal closing order; effects descriptor/finitewindowdependent','ligandfreeMD vsATP experiment;4.3ms experimentaltransient notMD inferredtime','n1perstart,correlatedframes,concrete next method withoutuniqueequilibriumclaim'])
 (c/'hidden/rubric.json').write_text(json.dumps({'core_units':units,'tolerances':{'distance_A':.02,'count':0},'subquestions':['direction or separation','amplitude or absolute state proximity','full transition or order boundary'],'source':'already independentlycheckedHSP/ADK native readouts','omission_boundary':'Split asks more explicit content; report coverage gain as task framing not improved latent reasoning'},ensure_ascii=False,indent=2))
(e/'DESIGN.json').write_text(json.dumps({'cases':['HSP90_Q01','Q-A1'],'arms':['ORIGINAL','SPLIT'],'replicates':4,'cap_usd':.40,'seed':2026091044,'success':'2of2cases improved supportedsubquestioncoverage without increasedoverclaim','same_scoring_within_case':True,'estimand':'explicit subquestion framing package vs original; not equivalent text length control'},indent=2));print(json.dumps(counts,ensure_ascii=False))
