import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
const req=createRequire(import.meta.url),mods=process.env.NODE_MODULES||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {marked}=req(path.join(mods,'marked'));const{chromium}=req(path.join(mods,'playwright'));
const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{for(const f of process.argv.slice(2)){
 const md=fs.readFileSync(f,'utf8');let html=marked.parse(md);html=html.replace(/src="([^"]+\.png)"/g,(_,src)=>'src="data:image/png;base64,'+fs.readFileSync(path.resolve(path.dirname(f),src)).toString('base64')+'"');
 let i=0,links=[];html=html.replace(/<h2>(.*?)<\/h2>/g,(_,t)=>{const id='section-'+(++i);links.push(`<a href="#${id}">${t}</a>`);return `<h2 id="${id}">${t}</h2>`});
 const title=md.split('\n')[0].replace(/^# /,'');const doc=`<!doctype html><html lang="${/_EN\.md$/.test(f)?'en':'zh-CN'}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{margin:0;background:#f5f6f8;color:#22303d;font:16px/1.85 -apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif}main{max-width:920px;margin:36px auto;background:white;padding:44px 56px}h1{font-size:30px;line-height:1.35;color:#1e3a5f}h2{font-size:23px;line-height:1.5;margin-top:38px;color:#1e3a5f}h3{font-size:19px;margin-top:25px}p{margin:14px 0}a{color:#275782;text-underline-offset:3px}table{border-collapse:collapse;width:100%;font-size:13px;line-height:1.6;margin:20px 0;table-layout:fixed;overflow-wrap:anywhere}th,td{border:1px solid #d5dbe1;padding:8px;vertical-align:top}th{background:#edf2f6}img{max-width:100%;height:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f4f7;padding:14px;font-size:12px}code{font-size:.88em;overflow-wrap:anywhere}nav{border-top:1px solid #ccd6df;border-bottom:1px solid #ccd6df;padding:12px 0}nav a{display:block;font-size:14px}blockquote{border-left:3px solid #1e3a5f;padding-left:16px;margin-left:0}@media(max-width:650px){main{padding:22px 18px;margin:0}h1{font-size:25px}table{font-size:11px}th,td{padding:5px}}@media print{body{background:white;font-size:14px;line-height:1.75}main{padding:0;margin:0;max-width:none}h1{font-size:24px}h2{font-size:18px;break-after:avoid}h3{font-size:14px;break-after:avoid}table{font-size:12px}tr,img,pre{break-inside:avoid}nav{display:none}a{color:inherit;text-decoration:none}p{orphans:3;widows:3}}</style><main>${html.replace(/(<\/h1>)/,'$1<nav>'+links.join('')+'</nav>')}</main></html>`;
 fs.writeFileSync(f.replace(/\.md$/,'.html'),doc);const page=await b.newPage();await page.setContent(doc);await page.pdf({path:f.replace(/\.md$/,'.pdf'),format:'A4',printBackground:true,margin:{top:'16mm',bottom:'16mm',left:'15mm',right:'15mm'},displayHeaderFooter:true,headerTemplate:'<span></span>',footerTemplate:'<div style="font-size:8px;width:100%;text-align:center;color:#777">Dynamics Atlas · <span class="pageNumber"></span> / <span class="totalPages"></span></div>'});await page.close();console.log(f);
}}finally{await b.close()}
