import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),P=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pptxgenjs'));
const p=new P();p.layout='LAYOUT_WIDE';p.author='Dynamics Atlas';p.title='Dynamics Atlas: scientific progress';
const slides=[
['Dynamics Atlas: a scientific answer comes first','A real HSP90 result is now auditable.\nRule benefit remains an open research question.\nNext: native-observable interpretation and a second system.','本报告把科学结果、Agent能力和Rules独立收益分开。文件名沿用v4交付命名，内容截至9月10日。'],
['The goal: connect evidence to a bounded answer','Different measurements reveal different properties.\nRules preserve conditions; tools produce evidence.\nAgents choose analyses and explain what follows.','结构、距离敏感实验与轨迹不测同一个量。项目G1–G4围绕可靠量、跨观测比较、复用流程和Agent辅助。'],
['Two meetings kept the project grounded','July 28: extract science from existing HSP90 data.\nAugust 24: show a minimum prototype using mature methods.\nExperts need a concrete result to critique.','来源为7月28日及8月24日会议纪要。会议支持最小原型，没有批准覆盖全部方法的自动系统。'],
['The path: data → rules → agent answers','July: HSP90 acquisition and analysis.\nAugust: source-grounded rules and routing prototype.\nSeptember: Q05 / T4L development, then four HSP90 answers.','33条候选规则是知识档案。规则映射和覆盖测试不能代替科学正确率。12次Q05/T4L运行是开发观察。'],
['HSP90: what changes after a closed-lid start?','20 closed-seeded and 20 open-seeded trajectories.\n1,001 saved points each, spanning 20–1020 ns.\nDirectional labels combine geometry and NOE preference.','NOE是对原子近距离敏感的核磁观测。起始来源不是平衡人口；相对违例更低也不等于绝对违例小。'],
['Half show open direction, through two different histories','At the five-point threshold, closed starts split:\n5 first qualify as open; 5 go closed → open; 10 stay closed.\nOpen starts: all 20 remain directionally open.','10/20=5+5。首个合格开放段不等于t=0开放。门槛20和50点下分区为5/4/9/2和7/1/10/2；不是驻留时间分布。'],
['A correct answer must keep definitions separate','ES15 has 906 open-direction points from 115 ns.\nAt 50 points, its first qualifying direction is already open.\nStrict core labels cover only 3 of 40,040 saved points.','5/4/1离开候选依赖首个持续方向定义。核心覆盖低是判据适配问题，不能推断没有真实变化。'],
['Three answers recover counts; rule value is not established','A1, B1 and B2 recover the main counts; A2 mixes thresholds.\nB2 adds a useful 10/20 observation.\nBoth B answers import RMP terms without established applicability.','A普通Agent，B额外Rules提示。四次费用0.0757458美元。未引用rule_id是输出设计问题；B1分箱措辞是局部问题。不能报告总体75%正确率。'],
['The bottleneck: turn work into usable delivery','Reuse verified analysis instead of repeating it.\nEvery track ends with an answer, evidence and meeting material.\nPreserve originals; preregister comparisons; no live answer hints.','早先审查快照确有缺交付。e2bfa35后已有简报、读本及deck，当前补完整时间线。文件存在不代表已给合作者发送。'],
['New evidence narrows interpretation; one runtime remains blocked','NOE at 1 A: 9 of 10 closed-start open-direction traces remain mostly far from both references.\nRules: scope rendering fixed; behavioral effect untested.\nSecond system: candidates found; credentials and admission pending.','B已完成40040点对照；18/20开放组阳性对照通过。初次读取列假设已在分类前修订。C已测试，D未运行。0.30美元新模型费、2GB下载、15工作日上限。科学推进不再以Rules增益为前提。']];
for(const[title,body,notes]of slides){let s=p.addSlide();s.addText(title,{x:.6,y:.4,w:12.1,h:1.1,fontSize:29,bold:true,color:'17365D',margin:0});s.addText(body,{x:.8,y:2,w:11.7,h:4.1,fontSize:25,color:'344454',breakLine:false,paraSpaceAfterPt:28,margin:0});s.addText('Dynamics Atlas | audited development evidence | '+p._slides.length,{x:.7,y:7,w:12,h:.2,fontSize:10,color:'666666'});s.addNotes(notes)}
await p.writeFile({fileName:process.argv[2]});
