const path=require('path'),fs=require('fs');
const pptxgen=require(path.join(process.env.HOME,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pptxgenjs'));
const root=path.resolve(__dirname,'..'),out=path.join(root,'outputs/report'); const ppt=new pptxgen();ppt.layout='LAYOUT_WIDE';ppt.author='Dynamics Atlas';ppt.subject='DHFR source-grounded local-contact analysis';ppt.title='DHFR local contacts and Agent input limits';ppt.lang='zh-CN';ppt.theme={headFontFace:'Arial',bodyFontFace:'Arial',lang:'zh-CN'};
let count=0;
function slide(title,body,notes){let s=ppt.addSlide();s.background={color:'FFFFFF'};s.addText(title,{x:.5,y:.35,w:12.2,h:.7,fontSize:27,bold:true,color:'243B64',margin:0});if(body)s.addText(body,{x:.6,y:1.35,w:12.05,h:4.85,fontSize:22,color:'243B64',breakLine:false,margin:0,paraSpaceAfterPt:18});s.addText('Çetin et al., JCIM 2023 • DOI 10.1021/acs.jcim.3c00818 • Zenodo 7966540',{x:.6,y:7.05,w:11.4,h:.18,fontSize:10,color:'687787',margin:0});s.addText(String(++count),{x:12.1,y:7,w:.4,h:.25,fontSize:12,color:'687787'});s.addNotes(notes+'\nDetailed reader: outputs/report/DEEP_READER_ZH.md. Developer post-freeze periodic diagnostic; original Agent answers preserved.');return s;}
slide('DHFR：特定尾部接触支持配体选择性，但未证明动力学因果','4′-DTMP 与 M20 环及 R28 的部分原子更接近\n\n四条作者沉积轨迹 · 两次普通 Agent 答复\n\n2026-09-10 | 第二体系结果与输入缺口', 'DHFR是叶酸代谢酶；TMP是甲氧苄啶，4DTMP是衍生抑制剂。WT与L28R分别为野生型及28位亮氨酸替换为精氨酸。区分开发者完成的科学补算与Agent真实执行。');
slide('论文用结构、亲和力和反应进程提出同一个配体问题','结构：哪些指定原子对更近？\n\n亲和力：两种抑制剂的 Ki 如何随 L28R 改变？\n\n反应：500 nM 抑制剂下，底物消耗如何变化？','主文Table1、Figures3–4分别提供Ki、实验曲线及原子对距离。三个观测不是同一个量。本文不复现自由能微扰或全蛋白网络。Ki的大小不能直接替代动力学速率。');
slide('四种条件各有一条沉积轨迹，可做明确的局部比较','WT / L28R × TMP / 4′-DTMP\n\n每条 1,001 帧；主窗口帧 11–1000，共 990 帧\n\n约 1.02 GB，作者校验值一致；未运行新模拟\n\n名义 1 μs 来自沉积说明；帧不是独立重复','四PSF与DCD，159蛋白残基，WT残基28LEU，突变ARG；TMP配体残基300，4DTMP303。时间映射从沉积说明推断，DCD头重写。实验His6标签与缓冲液不同于模拟，比较仅限条件特异模式。');
let s=slide('存储坐标的大距离主要来自周期性包装','', '灰色为未处理存储坐标，蓝色为最近镜像距离；该图同一条WT-TMP轨迹。最近镜像与VMD pbctools重包装后的距离最大差异1.132e-5Å。开发者在A1启动后才发现，这是建包责任。');s.addImage({path:path.join(out,'periodic_diagnostic.png'),x:.6,y:1.25,w:8.5,h:3.5});s.addText('先核坐标表示\n再解释接触\n\n原始试跑保留\n修正不计 Agent 成果',{x:9.4,y:1.7,w:3.1,h:3.8,fontSize:22,color:'243B64',margin:0});
const rows=JSON.parse(fs.readFileSync(path.join(root,'outputs/mic_diagnostic/ligand_comparison.json')));let sel=rows.filter(x=>['r18_O_O3P','r20_N_O3P','r22_O_O3P'].includes(x.atom_pair));s=slide('六项指定环区比较均显示 4′-DTMP 更近','', '每根柱为单条条件轨迹990帧均值，Å；未画跨重复误差。WT M20 8.69→4.62，L28R M20 10.44→4.81。结果来自开发者周期性补算，不是原Agent使用的数据。');s.addChart(ppt.ChartType.bar,[{name:'TMP',labels:sel.map(x=>x.variant.toUpperCase()+' '+x.atom_pair.split('_')[0]),values:sel.map(x=>x.TMP_mean_A)},{name:'4′-DTMP',labels:sel.map(x=>x.variant.toUpperCase()+' '+x.atom_pair.split('_')[0]),values:sel.map(x=>x['4DTMP_mean_A'])}],{x:.6,y:1.3,w:12,h:4.95,catAxisLabelFontSize:15,valAxisLabelFontSize:13,valAxisTitle:'Mean distance (Å)',showValue:true,dataLabelFormatCode:'0.0',showLegend:true,legendPos:'b',chartColors:['243B64','21918C'],showTitle:false,showBorder:false});
sel=rows.filter(x=>x.variant==='l28r'&&x.atom_pair.startsWith('r28_'));s=slide('R28 的变化依赖原子对，不能概括为全部增强','', 'L28R R28三个供体到O4P/O5P六项均更近。NE到O3P+0.13Å，NH1到O3P+0.39Å，NH2到O3P-0.71Å。指定原子对限制防止把局部结论扩大。');s.addChart(ppt.ChartType.bar,[{name:'4DTMP − TMP',labels:sel.map(x=>x.atom_pair.replace('r28_','')),values:sel.map(x=>x.delta_4DTMP_minus_TMP_A)}],{x:.6,y:1.35,w:12,h:4.95,catAxisLabelFontSize:13,valAxisLabelFontSize:13,valAxisTitle:'Change in mean distance (Å)',showValue:true,dataLabelFormatCode:'0.0',showLegend:false,chartColors:['21918C'],showBorder:false});
slide('实验方向相容，但距离不能给出抑制速率','Ki（TMP → 4′-DTMP）\nWT：4.2 → 5.1 nM；L28R：65.0 → 34.3 nM\n\n500 nM：WT 两药均抑制；L28R 的 4′-DTMP 更明显\n\n局部距离没有识别唯一因果机制','Table1误差WT±0.5/1.0nM，L28R±7.5/2.9nM。Ki来自论文ref25；图3初始DHF12.5μM，两次实验。没有原始动力学数据或FEP重算，不能声称动力学原因已独立证明。');
slide('两次 Agent 完成了计算，却没有发现输入的坐标缺口','两份有效答复；4 个 Python 请求全部原样重放一致\n\n模型费用合计 $0.03226009\n\nA1 有比例转述错误；A2 把异常长尾解释为构象变化\n\n原资料缺坐标和盒子，修正由开发者完成','A1输入106713输出8534tokens，21tools，77.19秒；A2输入75833输出5753tokens，17tools，50.41秒。各只提交一稿，未明确修订。没有Rules，不得作为Rules收益比较。8条逐答复关系各保存真实短引文。');
slide('下一步应复用正确的资料入口，不扩大 Rules 结论','已得到：有来源的 DHFR 局部接触结果\n\n需修好：冻结前的周期性坐标与物理量核对\n\n本轮结束：不补跑修正案例、不进入第三体系\n\n来源与复跑：配套读本、下载清单和原始答复','参考：Cetin etal2023 DOI10.1021/acs.jcim.3c00818；Zenodo7966540 CC-BY4.0；作者代码eba9948e57f25cec9eb9bdb50cfdb234fc23fffc；GROMACS2024.4 PBC方法；VMD2.0b1与pbctools。结果不能支持跨体系泛化或独立规则增益。');
ppt.writeFile({fileName:path.join(out,'COLLABORATOR_REPORT.pptx')});
