from pathlib import Path
import numpy as np,csv,json,subprocess,datetime
r=Path(__file__).resolve().parents[1];o=r/'outputs';spec={'frozen_before_calls':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pairs_residue_numbers':[[30,1],[67,115],[118,68],[160,214],[144,189],[149,188]],'preset_frames':'first, floor(n/2),last; additionally ALL frames evaluated, including every extent trigger','neighbor_max_A':4.5,'crosscheck_max_abs_error_A':.01,'extent':'record extent/L and extent/(L/2); conservative literal trigger extent/(L/2)>.5; intramolecular MIC prohibited in every case','representation':'contiguous CA chain validated; no image shifts required in these trajectories'};(o/'FOUR_STANDARD_PREFLIGHT_SPEC.json').write_text(json.dumps(spec,indent=2));checks={}
for state in ['open','closed']:
 a=np.loadtxt(r/f'derived/{state}_ca_raw.tsv');x=a[:,8:].reshape(-1,214,3);box=a[:,2:5];n=len(a);native=np.loadtxt(r/f'derived/{state}_native_xtc_headers.tsv');times=native[:,1];d=np.diff(x,axis=1);assert np.count_nonzero(np.round(d/box[:,None,:]))==0
 neighbors=np.linalg.norm(d,axis=-1);extent=np.ptp(x,axis=1);rat=extent/box;half_rat=2*rat;trigger=np.any(half_rat>.5,axis=1)
 maps=list(csv.DictReader((r/f'derived/{state}_atom_mapping.tsv').open(),delimiter='\t'));assert [int(z['resid'])for z in maps]==list(range(1,215));assert n==len(native);assert np.isfinite(x).all();assert np.all(np.diff(times)>0)
 nums=[int(maps[z-1]['index'])+1 for pair in spec['pairs_residue_numbers']for z in pair];sel=' plus '.join('atomnr '+str(z) for z in nums);out=o/f'gmx_allframes_{state}.xvg';cmd=['gmx','distance','-s',str(r/f'inputs/ORADD_{state}_state.gro'),'-f',str(r/f'inputs/ORADD_{state}_state_traj.xtc'),'-nopbc','-normpbc','-select',sel,'-oall',str(out)];p=subprocess.run(cmd,capture_output=True,text=True);(o/f'gmx_allframes_{state}.log').write_text(p.stdout+p.stderr);assert p.returncode==0,p.stderr[-1000:]
 vals=np.array([list(map(float,l.split()))for l in out.read_text().splitlines()if l and l[0]not in '#@']);assert vals.shape==(n,7),vals.shape;assert np.allclose(vals[:,0],times,atol=.01)
 local=np.column_stack([np.linalg.norm(x[:,i-1]-x[:,j-1],axis=1)for i,j in spec['pairs_residue_numbers']]);err=np.max(abs(vals[:,1:]*10-local));passed=bool(neighbors.max()<=4.5 and err<=.01)
 np.savetxt(r/f'derived/{state}_axis_extents.tsv',np.column_stack([times/1000,extent,rat,half_rat,trigger.astype(int)]),delimiter='\t',header='time_ns extent_x_A extent_y_A extent_z_A ratio_L_x ratio_L_y ratio_L_z ratio_halfL_x ratio_halfL_y ratio_halfL_z literal_trigger')
 checks[state]={'status':'PASS'if passed else'FAIL','nframes':n,'preset_frames':[0,n//2,n-1],'trigger_frames':np.flatnonzero(trigger).tolist(),'gmx_checked_frames':n,'checked_pairs':spec['pairs_residue_numbers'],'max_abs_error_A':float(err),'adjacent_CA_max_A':float(neighbors.max()),'max_extent_over_L_xyz':rat.max(axis=0).tolist(),'max_extent_over_halfL_xyz':half_rat.max(axis=0).tolist(),'box_range_A':[float(box.min()),float(box.max())],'units_mapping_time':'PASS','no_chain_image_shifts':True}
result={'status':'PASS'if all(v['status']=='PASS'for v in checks.values())else'FAIL','time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'systems':checks,'scope':'Predefined six pairs on ALL frames, not all N-squared pairs. Continuity on every adjacent CA in every frame. No claim of equilibrium or experimental validation.'};(o/'FOUR_STANDARD_PHYSICAL_ADMISSION.json').write_text(json.dumps(result,indent=2));print(json.dumps({s:{k:v for k,v in c.items()if k!='trigger_frames'}for s,c in checks.items()},indent=2))
